#!/bin/bash
#java -cp /usr/share/java/antlr3.jar:/home/posnett/work/jstyle/antlr/try2/ JStyle $@
java -cp /usr/share/java/antlr3.jar:.:$HOME/projects/ngrams/antlr LexJava $@ | $HOME/projects/ngrams/bin/codejoin.sh
